"""add other task assessments

Revision ID: 0f123fa6d1e4
Revises: e342c9966266
Create Date: 2025-02-19 11:00:06.701820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f123fa6d1e4'
down_revision: Union[str, None] = 'e342c9966266'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("experiment_turn") as batch:
        batch.add_column(sa.Column('other_task', sa.String(), server_default='', nullable=False))
        batch.add_column(sa.Column('other_task_assessment', sa.String(), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("experiment_turn") as batch:
        batch.drop_column('other_task_assessment')
        batch.drop_column('other_task')
    # ### end Alembic commands ###
