"""add reviews

Revision ID: 540ca9430553
Revises: 0b5affcd8969
Create Date: 2024-07-02 16:25:07.378245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '540ca9430553'
down_revision: Union[str, None] = '0b5affcd8969'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('questionrelevent', sa.Integer(), nullable=False),
    sa.Column('questionfromarticle', sa.Integer(), nullable=False),
    sa.Column('questionindependence', sa.Integer(), nullable=False),
    sa.Column('questionchallenging', sa.Integer(), nullable=False),
    sa.Column('answerrelevent', sa.Integer(), nullable=False),
    sa.Column('answercomplete', sa.Integer(), nullable=False),
    sa.Column('answerfromarticle', sa.Integer(), nullable=False),
    sa.Column('answerunique', sa.Integer(), nullable=False),
    sa.Column('answeruncontroverial', sa.Integer(), nullable=False),
    sa.Column('arithmaticfree', sa.Integer(), nullable=False),
    sa.Column('skillcorrect', sa.Integer(), nullable=False),
    sa.Column('domaincorrect', sa.Integer(), nullable=False),
    sa.Column('comments', sa.String(), nullable=False),
    sa.Column('accept', sa.Boolean(), nullable=False),
    sa.Column('modified', sa.DateTime(), nullable=False, default=sa.func.now()),
    sa.ForeignKeyConstraint(['author_id'], ['author.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review')
    # ### end Alembic commands ###
