"""add modification date

Revision ID: 622411ddf926
Revises: 9f0056208d47
Create Date: 2025-02-25 13:45:13.461896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '622411ddf926'
down_revision: Union[str, None] = '9f0056208d47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("experiment_log") as b:
        b.add_column(sa.Column('modified', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("experiment_log") as b:
        b.drop_column('modified')
    # ### end Alembic commands ###
