"""nonscore labstyle additions

Revision ID: e342c9966266
Revises: 61e36b800a0f
Create Date: 2025-02-19 10:50:19.946643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e342c9966266'
down_revision: Union[str, None] = '61e36b800a0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("preliminary_evaluation") as batch:
        batch.add_column(sa.Column('reasoning_experience_id', sa.Integer(), nullable=True))
        batch.add_column(sa.Column('difficulty_explaination', sa.String(), server_default='', nullable=False))
        batch.add_column(sa.Column('realism', sa.String(), server_default='', nullable=False))
        batch.add_column(sa.Column('goal', sa.String(), server_default='', nullable=False))
        batch.add_column(sa.Column('comments', sa.String(), server_default='', nullable=False))
        batch.create_foreign_key('reasoning_experience_id', 'ai_skill', ['reasoning_experience_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("preliminary_evaluation") as batch:
        batch.drop_constraint('reasoning_experience_id',  type_='foreignkey')
        batch.drop_column('comments')
        batch.drop_column('goal')
        batch.drop_column('realism')
        batch.drop_column('difficulty_explaination')
        batch.drop_column('reasoning_experience_id')
    # ### end Alembic commands ###
